### ISSUE TITLE
Using filters

### ISSUE THREAD

**Issue by the-evocative-eye** [ContriHUB/User-management-system#1]
We can enhance the search query part by adding some filters.

Just as when we write some SQL query, let's say we want to figure out the top 10 queries or maybe the nth query, then is it possible to use this query and apply either of these filters to come up with the desired table result?

This will enhance the functionality of CLI and user interaction, also using this feature the bifurcation among a large heap of data and chunks of these required will be much easier.

We already have that find function, for more if we can add just one filter of the top n queries table.
Example: in the find part let's say I search 'computer science' it will give all entries pertaining to this 'computer science' keyword, now what we can do, let's suppose I just want to fetch the top 10 rows of this table, I think we can implement this subpart making one extra icon of filter, and when user enter top 5, it straightaway catches the n=5 and runs a loop for this value of n within filter function, connection of both 'find' and 'filter' APIs would be required to make them function together.
https://dev.to/alexmercedcoder/making-multiple-api-calls-in-javascript-kip (Can refer to this on how to call two APIs simultaneously).

**Comment by rituraj12797** [comment]
i want to work on this issue please assign me

**Comment by Madhav-495** [comment]
@the-evocative-eye do we have to implement find and filter api separately and then user will call find and filter api or in filter api we just need to do it

**Comment by the-evocative-eye** [comment]
See it depends agr ek hi jgah, I mean find query ke andar hi  top n query ke lie train kardo, ya phr alag se bhi column bana skte, but i suggest ki try doing it within find, alag se banane ki jgah

**Comment by Madhav-495** [comment]
I guess n should be taken as parameter and filter function should filter only top n query not on the basis of most searched or something like that . Clarify This

**Comment by the-evocative-eye** [comment]
It is arranged on first come, first serve, just as data is being displayed in ArrayList in Java or vector in cpp, so when you try to fetch the first n records, it should automatically give the first n records, it is nothing to do with 'most searched'.

**Comment by the-evocative-eye** [comment]
Any updates @Madhav-495 ?

**Comment by Madhav-495** [comment]
will be making pull request after 2-3 hrs

**Comment by Madhav-495** [comment]
@the-evocative-eye submited the pr . kindly review
