### ISSUE TITLE
Change the color

### ISSUE THREAD

**Issue by the-evocative-eye** [ContriHUB/User-management-system#3]
![Screenshot (24)](https://github.com/ContriHUB/User-management-system/assets/97403811/f3ab96ff-e299-42da-afa3-1cc3820506c2)
If we can have separate colors for active status ones and inactive status ones when we hover over the row.

**Comment by madmecodes** [comment]
@the-evocative-eye  Pls assign me this issue i know how to solve this.

**Comment by Petsamuel** [comment]
@the-evocative-eye i'm intrested in this issue

**Comment by the-evocative-eye** [comment]
You need to first request this issue from contrihub website.
