### ISSUE TITLE
Grouping of rows

### ISSUE THREAD

**Issue by the-evocative-eye** [ContriHUB/User-management-system#4]
![Screenshot (24)](https://github.com/ContriHUB/User-management-system/assets/97403811/5e8f267e-9b98-4865-8fe0-524419c3b6ef)
Grouping the data with active status over inactive status, right now it is arranged based on first come, first serve.
This feature will ease the user readability. You can try doing it like this is the home page, so go to this home page.js->find how it is displaying data, and try applying the 'group by'(js query has this feature) based on active or inactive functionality to that data.

**Comment by Madhurgupta12** [comment]
please assign this issue

**Comment by the-evocative-eye** [comment]
You are supposed to send the request through the contriHUB website for this issue to get assigned.

**Comment by Manan-Arora31** [comment]
@the-evocative-eye I am getting this error
![Screenshot 2023-10-10 222846](https://github.com/ContriHUB/User-management-system/assets/115869448/44e03522-0ac8-400d-92c4-685bcc525798)

**Comment by the-evocative-eye** [comment]
What all you did, how are you approaching it, that leads to this error

**Comment by the-evocative-eye** [comment]
I have used MongoDb cloud for this, so it seems to me a connection error,
try with some better network, or probably do one thing, login to the
MongoDb atlas with ur credentials,then try to connect, if error still
persist, bta denaa

**Comment by Manan-Arora31** [comment]
Yes @the-evocative-eye this error is resolved now. I have solved this issue in PR#7. Please check if any changes are required.

**Comment by the-evocative-eye** [comment]
> Yes @the-evocative-eye this error is resolved now. I have solved this issue in PR#7. Please check if any changes are required.

What is the relevance of 'i+1' here, if you have taken the 'j' variable as ID?

**Comment by Manan-Arora31** [comment]
@the-evocative-eye I have used j for id in my code. And haven't used i + 1 anywhere. Please clarify.

![Screenshot 2023-10-12 224322](https://github.com/ContriHUB/User-management-system/assets/115869448/174dd885-dd55-410f-9183-717bf7cebf78)
![Screenshot 2023-10-12 224331](https://github.com/ContriHUB/User-management-system/assets/115869448/5aaed91f-435b-4c3c-816e-0412ebd79149)

**Comment by Manan-Arora31** [comment]
@the-evocative-eye There were a couple of occasions where was some misunderstanding, and this did contribute to some delays in the resolution. I believe that, without these issues, I would have been able to complete the task within the specified deadline.

**Comment by the-evocative-eye** [comment]
Apart from misunderstanding, you already exceeded the deadline of the
issue, we were working on extended deadline, because the entire task wasn't
completed, that jumbled ID one. Other than that, great work!
