### ISSUE TITLE
Audit History

### ISSUE THREAD

**Issue by the-evocative-eye** [ContriHUB/User-management-system#5]
We do have the functionality of updating and deleting in this application but maintaining the history of who has done this and at what time elapse it has been done, is missing. 

You can try doing it by going to the update functionality in 'controller. js'(it controls the entire backend) when the user is trying to update a column by ID, add a compulsory middleware, or maybe a function within 'exports. update' to include the name of the user who is trying to update and in the backend, we should have an audit history consisting of the name and time(we have javascript objects for date and time, can use that) at which it has been updated.
This same functionality must be included in the delete portion too. 

[https://learn.microsoft.com/en-us/power-apps/developer/data-platform/auditing/retrieve-audit-data?tabs=webapi](url)
Can read this to get more clarification.

**Comment by reharsh** [comment]
can you assign this issue to me, already requested on contriHub.

**Comment by the-evocative-eye** [comment]
done.

**Comment by reharsh** [comment]
@the-evocative-eye ma'am, I am unable to connect to mongo cluster and getting this error
Server is listening on http://localhost:3000
Error: querySrv ENOTFOUND _mongodb._tcp.cluster0.uzcbc7v.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17) {
  errno: undefined,
  code: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.cluster0.uzcbc7v.mongodb.net'
}
PS: already downloaded all dependencies including dotenv
also where to ask further queries(if any), here or any other platform like discord/mail?
thanks

**Comment by the-evocative-eye** [comment]
> @the-evocative-eye ma'am, I am unable to connect to mongo cluster and getting this error Server is listening on http://localhost:3000 Error: querySrv ENOTFOUND _mongodb._tcp.cluster0.uzcbc7v.mongodb.net at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17) { errno: undefined, code: 'ENOTFOUND', syscall: 'querySrv', hostname: '_mongodb._tcp.cluster0.uzcbc7v.mongodb.net' } PS: already downloaded all dependencies including dotenv also where to ask further queries(if any), here or any other platform like discord/mail? thanks

Did you allow all network access on [www.mongodb.com](url),
see these might be the steps you need to follow after local setup to connect to the virtual mongo cloud, go to [www.mongodb.com](url)->create your project-> form a cluster within it -> now have that database access(it might be on the left side) -> then go to network access -> within that allow your clusters to be accessible from all localhosts.
For further queries, you can ask here itself, or you can also mail me(taniyaagarwal085@gmail.com).

**Comment by reharsh** [comment]
@the-evocative-eye ma'am, submitted a PR please look into it.
